# frontend/nginx.conf
server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  client_max_body_size 12m;

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:js|css|woff2?|ttf|svg|png|jpg|webp|ico)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
  }
}
