"""contents tags views

Revision ID: 175c88b7c9d3
Revises: e5a37cc5f33d
Create Date: 2026-04-21 14:23:57.465202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '175c88b7c9d3'
down_revision: Union[str, Sequence[str], None] = 'e5a37cc5f33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('view_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('oss_bucket', sa.String(length=64), nullable=False),
    sa.Column('oss_object_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=32), server_default=sa.text("'public_in_site'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','deleted')", name='ck_contents_status'),
    sa.CheckConstraint("visibility IN ('public_in_site','private')", name='ck_contents_visibility'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contents_sha256', 'contents', ['sha256'], unique=False)
    op.create_index('ix_contents_uploader_created', 'contents', ['uploader_id', 'created_at'], unique=False)
    op.create_index('ix_contents_visibility_created', 'contents', ['visibility', 'created_at'], unique=False)
    op.create_table('content_tags',
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'tag_id')
    )
    op.create_index('ix_content_tags_tag', 'content_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_tags_tag', table_name='content_tags')
    op.drop_table('content_tags')
    op.drop_index('ix_contents_visibility_created', table_name='contents')
    op.drop_index('ix_contents_uploader_created', table_name='contents')
    op.drop_index('ix_contents_sha256', table_name='contents')
    op.drop_table('contents')
    op.drop_table('view_logs')
    op.drop_table('tags')
    # ### end Alembic commands ###
